name: Test Python Script Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        os:
          - ubuntu-latest
        arch:
          - x64


    steps:
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.12 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Execute Python script # Run the run.py to get the latest data
        run: python run.py