name: Test Python Script Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     node-version: [20]
    #     os:
    #       - ubuntu-latest
    #     arch:
    #       - x64


    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # specify the version of Node.js you want to use
          cache: 'npm' # cache npm dependencies to speed up builds

      # - name: Checkout repository content
      #   uses: actions/checkout@v4 # Checkout the repository content to github runner.


      # - name: Setup Python Version
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.12 # Install the python version needed

      # - name: Install Python dependencies
      #   run: python -m pip install --upgrade pip requests

      # - name: Execute Python script # Run the run.py to get the latest data
      #   run: python run.py